---
title: "NIOZ164_EUX_discs_tidy_data"
author: Maaike Goudriaan, MMB, NIOZ
output: html_document
date: "2023-08-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/Maaike/Documents/Github/Caribbean_discs_longterm")
```

## Load relevant libraries
```{r libaries, echo = F}
library(devtools)
library(phyloseq)
library(grid)
library(tidyverse)
library(vegan)
library(rmarkdown)
library(knitr)
library(microbiome)
```

## Load data
```{r load data, echo= F}
tax <- as.matrix(read.delim('../Data/representative_seq_set_tax_assignments.txt', row.names = 1, na.strings = c(" ")))
tax <- tax_table(tax)
otu <- read.delim('../Data/asvTable.txt', row.names = 1)
otu <- otu %>%  select(-taxonomy) %>% as.matrix() 
otu <- otu_table(otu, taxa_are_rows = T)
map <- sample_data(read.delim('../Data/Metadata_EUX_Discs.txt', row.names = 1, na.strings = c("")))
```

```{r Create phyloseq object and check}
physeq_object = merge_phyloseq(otu, tax, map)
summarize_phyloseq(physeq_object) 

source("basic_info_physeq_object.R")
basic_info_physeq_object(physeq_object)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
